Minimarket_Raphi/Models/Subfamilia_Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subfamilia_Producto
    {
        public string ID_SubfamiliaProducto { get; set; }
        public string Subfamilia { get; set; }
    }
}

Minimarket_Raphi/Controllers/Subfamilia_ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Minimarket_Raphi.Datos;
using Minimarket_Raphi.Models;

namespace Minimarket_Raphi.Controllers
{
    public class Subfamilia_ProductoController : Controller
    {
        Subfamilia_ProductoAdmin admin = new Subfamilia_ProductoAdmin();
        // GET: Empleado
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }
        public ActionResult Detalle(string id)
        {
            return View(admin.Consultar(id));
        }
        public ActionResult Crear()
        {
            return View();
        }
        public ActionResult Guardar(Subfamilia_Producto modelo)
        {
            admin.Guardar(modelo); return View("Crear", modelo);
        }
        public ActionResult Editar(string id)
        {
            return View(admin.Consultar(id));
        }
        public ActionResult Modificar(Subfamilia_Producto modelo)
        {
            admin.Modificar(modelo); return View("Editar", modelo);
        }
        public ActionResult Eliminar(string id)
        {
            Subfamilia_Producto modelo = admin.Consultar(id);
            admin.Eliminar(modelo);
            return View("Index", admin.Consultar());
        }
    }
}

Minimarket_Raphi/Views/Subfamilia_Producto/Crear.cshtml
@model Minimarket_Raphi.Models.Subfamilia_Producto

@{
    ViewBag.Title = "Crear";
}
<div class="jumbotron">
    <h2>Crear</h2>


    @using (Html.BeginForm("Guardar", "Subfamilia_Producto", FormMethod.Post, new
    {
        @class = "form-horizontal",
        role = "form"
    }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Subfamilia_Producto</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ID_SubfamiliaProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_SubfamiliaProducto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_SubfamiliaProducto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Subfamilia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subfamilia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subfamilia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Minimarket_Raphi/Views/Subfamilia_Producto/Detalle.cshtml
@model Minimarket_Raphi.Models.Subfamilia_Producto

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Subfamilia_Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_SubfamiliaProducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_SubfamiliaProducto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subfamilia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subfamilia)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_SubfamiliaProducto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Minimarket_Raphi/Views/Subfamilia_Producto/Editar.cshtml
@model Minimarket_Raphi.Models.Subfamilia_Producto

@{
    ViewBag.Title = "Editar";
}
<div class="jumbotron">
    <h2>Editar</h2>


    @using (Html.BeginForm("Modificar", "Subfamilia_Producto", FormMethod.Post, new
    {
        @class = "formhorizontal",
        role = "form"
    }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Subfamilia_Producto</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_SubfamiliaProducto)

            @Html.HiddenFor(model => model.Subfamilia)

            <div class="form-group">
                @Html.LabelFor(model => model.ID_SubfamiliaProducto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID_SubfamiliaProducto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_SubfamiliaProducto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Subfamilia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subfamilia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subfamilia, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

Minimarket_Raphi/Views/Subfamilia_Producto/Eliminar.cshtml
@model Minimarket_Raphi.Models.Subfamilia_Producto

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subfamilia_Producto</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Minimarket_Raphi/Views/Subfamilia_Producto/Index.cshtml
@model IEnumerable<Minimarket_Raphi.Models.Subfamilia_Producto>

@{
    ViewBag.Title = "Administración de Subfamilias";
}
<div class="jumbotron">
    <h2>Tabla Subfamilia Producto</h2>

    <p>
        @Html.ActionLink("Agregar Nuevo", "Create", "Subfamilia_Producto/Crear")
    </p>
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID_SubfamiliaProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subfamilia)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_SubfamiliaProducto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subfamilia)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Editar", new { id = item.Subfamilia }) |
                    @Html.ActionLink("Details", "Detalle", new { id = item.Subfamilia }) |
                    @Html.ActionLink("Delete", "Eliminar", new { id = item.Subfamilia })
                </td>
            </tr>
        }
    </table>
</div>