Minimarket_Raphi/Models/Kardex.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kardex()
        {
            this.Hoja_de_Registro = new HashSet<Hoja_de_Registro>();
        }
    
        public string ID_Kardex { get; set; }
        public decimal Saldo_Inicial { get; set; }
        public Nullable<decimal> Saldo_Final { get; set; }
        public decimal Monto_Venta { get; set; }
        public string Codigo_Empleado { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoja_de_Registro> Hoja_de_Registro { get; set; }
    }
}

Minimarket_Raphi/Controllers/KardexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Minimarket_Raphi.Datos;
using Minimarket_Raphi.Models;

namespace Minimarket_Raphi.Controllers
{
    public class KardexController : Controller
    {
        KardexAdmin admin = new KardexAdmin();
        // GET: Kardex
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }
        public ActionResult Detalle(string id)
        {
            return View(admin.Consultar(id));
        }
        public ActionResult Crear()
        {
            return View();
        }
        public ActionResult Guardar(Kardex modelo)
        {
            admin.Guardar(modelo); return View("Crear", modelo);
        }
        public ActionResult Editar(string id)
        {
            return View(admin.Consultar(id));
        }

        // Se agrego solo el siguiente fragmento de codigo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(String id, Kardex datosUpdate)
        {
            try
            {
                admin.Consultar(id);

                if (admin != null)
                {
                    admin.Modificar(datosUpdate);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // Hasta aqui

        public ActionResult Modificar(Kardex modelo)
        {
            admin.Modificar(modelo); return View("Editar", modelo);
        }
        public ActionResult Eliminar(string id)
        {
            Kardex modelo = admin.Consultar(id);
            admin.Eliminar(modelo);
            return View("Index", admin.Consultar());
        }










        public ActionResult NuevoKardex(string ID_Kardex, Nullable<decimal> Saldo_Inicial, Nullable<decimal> Saldo_Final, Nullable<decimal> Monto_Venta, string Codigo_Empleado, Nullable<decimal> Ganancia, Nullable<int> Dia, Nullable<int> Mes, Nullable<int> Anio)
        {
            if (Codigo_Empleado == null)
            {
                return View();
            }
            else
            {
                Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                Nuevo.sp_nuevo_kardex(ID_Kardex, Saldo_Inicial, Saldo_Final, Monto_Venta, Codigo_Empleado, Ganancia, Dia, Mes, Anio);
                Nuevo.SaveChanges();
                return View();
            }
        }
        public ActionResult ActualizarKardex(string ID_Kardex, Nullable<decimal> Saldo_Inicial, Nullable<decimal> Saldo_Final, Nullable<decimal> Monto_Venta, string Codigo_Empleado, Nullable<decimal> Ganancia, Nullable<int> Dia, Nullable<int> Mes, Nullable<int> Anio)
        {
            if (Codigo_Empleado == null)
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    return View(contexto.Kardex.AsNoTracking().ToList());
                }
            }
            else
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                    Nuevo.sp_actualizar_kardex(ID_Kardex, Saldo_Inicial, Saldo_Final, Monto_Venta, Codigo_Empleado, Ganancia, Dia, Mes, Anio);
                    Nuevo.SaveChanges();
                    return View(contexto.Kardex.AsNoTracking().ToList());
                }
            }

        }
        public ActionResult EliminarKardex(string Codigo_Kardex)
        {
            if (Codigo_Kardex == null)
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    return View(contexto.Kardex.AsNoTracking().ToList());
                }
            }
            else
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {

                    Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                    Nuevo.sp_eliminar_kardex(Codigo_Kardex);
                    Nuevo.SaveChanges();
                    return View(contexto.Kardex.AsNoTracking().ToList());
                }
            }
        }







    }
}

Minimarket_Raphi/Views/Kardex/ActualizarKardex.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Kardex>
@{
    ViewBag.Title = "ActualizarKardex";
}
<div class="jumbotron">
    <h2>Actualizar Kardex</h2>
    @using (Html.BeginForm("ActualizarKardex", "Kardex", FormMethod.Post))
    {
        <style>
            div {
                margin-bottom: 10px;
            }

            label {
                display: inline-block;
                width: 150px;
                text-align: right;
            }
        </style>
        @Html.Label("Ingrese ID Kardex:")
        @Html.TextBox("ID_Kardex")
        <br>
        @Html.Label("Ingrese Saldo Inicial:")
        @Html.TextBox("Saldo_Inicial")
        <br>
        @Html.Label("Ingrese Saldo Final:")
        @Html.TextBox("Saldo_Final")
        <br>
        @Html.Label("Ingrese Monto Venta:")
        @Html.TextBox("Monto_Venta")
        <br>
        @Html.Label("Ingrese Código Empleado:")
        @Html.TextBox("Codigo_Empleado")
        <br>
        @Html.Label("Ingrese Ganancia")
        @Html.TextBox("Ganancia")
        <br>
        @Html.Label("Ingrese Día:")
        @Html.TextBox("Dia")
        <br>
        @Html.Label("Ingrese Mes:")
        @Html.TextBox("Mes")
        <br>
        @Html.Label("Ingrese Año:")
        @Html.TextBox("Anio")
        <br>

        <input type="submit" class="btn btn-success" value="Enviar">
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID_Kardex)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Saldo_Inicial)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Saldo_Final)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Monto_Venta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo_Empleado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ganancia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Anio)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_Kardex)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Saldo_Inicial)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Saldo_Final)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monto_Venta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ganancia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Anio)
                    </td>
                </tr>
            }
        </table>
    }
</div>

Minimarket_Raphi/Views/Kardex/EliminarKardex.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Kardex>
@{
    ViewBag.Title = "EliminarKardex";
}
<div class="jumbotron">
    <h2>Eliminar Kardex</h2>
    @using (Html.BeginForm("EliminarEmpleado", "Kardex", FormMethod.Post))
    {
        @Html.Label("Ingrese código para borrar:")
        @Html.TextBox("Codigo_Empleado")
        <br>

        <input type="submit" class="btn btn-success" value="Enviar">

        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID_Kardex)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Saldo_Inicial)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Saldo_Final)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Monto_Venta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo_Empleado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ganancia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Anio)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_Kardex)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Saldo_Inicial)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Saldo_Final)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monto_Venta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ganancia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Anio)
                    </td>
                </tr>
            }
        </table>
    }
</div>

Minimarket_Raphi/Views/Kardex/Index.cshtml
@model IEnumerable<Minimarket_Raphi.Models.Kardex>

@{
    ViewBag.Title = "Kardex";
}
<div class="jumbotron">
    <h2>Tabla Kardex</h2>
    @Html.ActionLink("NuevoKardex", "NuevoKardex", "Kardex", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("ActualizarKardex", "ActualizarKardex", "Kardex", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("EliminarKardex", "EliminarKardex", "Kardex", null, new { @class = "btn btn-primary btn-lg" })

    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID_Kardex)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo_Inicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo_Final)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Monto_Venta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Codigo_Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ganancia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anio)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_Kardex)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Saldo_Inicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Saldo_Final)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Monto_Venta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ganancia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Anio)
                </td>

            </tr>
        }
    </table>
</div>

Minimarket_Raphi/Views/Kardex/NuevoKardex.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Kardex>
@{
    ViewBag.Title = "NuevoKardex";
}
<div class="jumbotron">
    <h2>Nuevo Kardex</h2>
    @using (Html.BeginForm("NuevoKardex", "Kardex", FormMethod.Post))
    {
        <style>
            div {
                margin-bottom: 10px;
            }

            label {
                display: inline-block;
                width: 150px;
                text-align: right;
            }
        </style>

        @Html.Label("Ingrese ID Kardex:")
        @Html.TextBox("ID_Kardex")
        <br>
        @Html.Label("Ingrese Saldo Inicial:")
        @Html.TextBox("Saldo_Inicial")
        <br>
        @Html.Label("Ingrese Saldo Final:")
        @Html.TextBox("Saldo_Final")
        <br>
        @Html.Label("Ingrese Monto Venta:")
        @Html.TextBox("Monto_Venta")
        <br>
        @Html.Label("Ingrese Código Empleado:")
        @Html.TextBox("Codigo_Empleado")
        <br>
        @Html.Label("Ingrese Ganancia")
        @Html.TextBox("Ganancia")
        <br>
        @Html.Label("Ingrese Día:")
        @Html.TextBox("Dia")
        <br>
        @Html.Label("Ingrese Mes:")
        @Html.TextBox("Mes")
        <br>
        @Html.Label("Ingrese Año:")
        @Html.TextBox("Anio")
        <br>


        <input type="submit" class="btn btn-success" value="Enviar">

    }
</div>