Minimarket_Raphi/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string Codigo_Empleado { get; set; }
        public decimal Sueldo { get; set; }
        public string Nombre_Pila { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public string Accion_Ejecutada { get; set; }
    }
}

Minimarket_Raphi/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Minimarket_Raphi.Datos;
using Minimarket_Raphi.Models;

namespace Minimarket_Raphi.Controllers
{
    public class EmpleadoController : Controller
    {
        EmpleadoAdmin admin = new EmpleadoAdmin();
        // GET: Empleado
        public ActionResult Index()
        {
            return View(admin.Consultar());
        }
        public ActionResult Detalle(string id)
        {
            return View(admin.Consultar(id));
        }
        public ActionResult Crear()
        {
            return View();
        }
        public ActionResult Guardar(Empleado modelo)
        {
            admin.Guardar(modelo); return View("Crear", modelo);
        }
        public ActionResult Editar(string id)
        {
            return View(admin.Consultar(id));
        }

        // Se agrego solo el siguiente fragmento de codigo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(String id, Empleado datosUpdate)
        {
            try
            {
                admin.Consultar(id);

                if(admin != null)
                {
                    admin.Modificar(datosUpdate);
                }

                return RedirectToAction(nameof(Index));
            } catch
            {
                return View();
            }
        }
        // Hasta aqui

        public ActionResult Modificar(Empleado modelo)
        {
            admin.Modificar(modelo); return View("Editar", modelo);
        }
        public ActionResult Eliminar(string id)
        {
            Empleado modelo = admin.Consultar(id);
            admin.Eliminar(modelo);
            return View("Index", admin.Consultar());
        }








        public ActionResult NuevoEmpleado(string Codigo_Empleado, Nullable<decimal> Sueldo, string Nombre_Pila, string Apellido_Paterno, string Apellido_Materno, Nullable<System.DateTime> Fecha_Modificacion, string Accion_Ejecutada)
        {
            if (Codigo_Empleado == null)
            {
                return View();
            }
            else
            {
                Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                Nuevo.sp_nuevo_empleado(Codigo_Empleado, Sueldo, Nombre_Pila, Apellido_Paterno, Apellido_Materno, Fecha_Modificacion, Accion_Ejecutada);
                Nuevo.SaveChanges();
                return View();
            }
        }
        public ActionResult ActualizarEmpleado(string Codigo_Empleado, Nullable<decimal> Sueldo, string Nombre_Pila, string Apellido_Paterno, string Apellido_Materno, Nullable<System.DateTime> Fecha_Modificacion, string Accion_Ejecutada)
        {
            if (Codigo_Empleado == null)
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    return View(contexto.Empleado.AsNoTracking().ToList());
                }
            }
            else
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                    Nuevo.sp_actualizar_empleado(Codigo_Empleado, Sueldo, Nombre_Pila, Apellido_Paterno, Apellido_Materno, Fecha_Modificacion, Accion_Ejecutada);
                    Nuevo.SaveChanges();
                    return View(contexto.Empleado.AsNoTracking().ToList());
                }
            }

        }
        public ActionResult EliminarEmpleado(string Codigo_Empleado)
        {
            if (Codigo_Empleado == null)
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {
                    return View(contexto.Empleado.AsNoTracking().ToList());
                }
            }
            else
            {
                using (Minimarket_RaphiEntities contexto = new Minimarket_RaphiEntities())
                {

                    Minimarket_RaphiEntities Nuevo = new Minimarket_RaphiEntities();
                    Nuevo.sp_eliminar_empleado(Codigo_Empleado);
                    Nuevo.SaveChanges();
                    return View(contexto.Empleado.AsNoTracking().ToList());
                }
            }
        }










    }
}

Minimarket_Raphi/Views/Empleado/ActualizarEmpleado.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Empleado>
@{
    ViewBag.Title = "Actualizar Empleado";
}
<div class="jumbotron">
    <h2>Actualizar Empleado</h2>
    @using (Html.BeginForm("ActualizarEmpleado", "Empleado", FormMethod.Post))
    {
        <style>
            div {
                margin-bottom: 10px;
            }

            label {
                display: inline-block;
                width: 150px;
                text-align: right;
            }
        </style>
        @Html.Label("Ingrese código:")
        @Html.TextBox("Codigo_Empleado")
        <br>
        @Html.Label("Ingrese Nombre:")
        @Html.TextBox("Nombre_Pila")
        <br>
        @Html.Label("Ingrese Apellido Paterno:")
        @Html.TextBox("Apellido_Paterno")
        <br>
        @Html.Label("Ingrese Apellido Materno:")
        @Html.TextBox("Apellido_Materno")
        <br>
        @Html.Label("Ingrese Sueldo:")
        @Html.TextBox("Sueldo")
        <br>
        @Html.Label("Fecha de Modificación")
        @Html.TextBox("Fecha_Modificacion")
        <br>
        @Html.Label("Acción Ejecutada:")
        @Html.TextBox("Accion_Ejecutada")
        <br>

        <input type="submit" class="btn btn-success" value="Enviar">

        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo_Empleado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sueldo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre_Pila)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido_Paterno)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sueldo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre_Pila)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido_Paterno)
                    </td>
                </tr>
            }
        </table>


    }
</div>

Minimarket_Raphi/Views/Empleado/EliminarEmpleado.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Empleado>
@{
    ViewBag.Title = "EliminarEmpleado";
}
<div class="jumbotron">
    <h2>Eliminar Empleado</h2>
    @using (Html.BeginForm("EliminarEmpleado", "Empleado", FormMethod.Post))
    {
        @Html.Label("Ingrese código para borrar:")
        @Html.TextBox("Codigo_Empleado")
        <br>

        <input type="submit" class="btn btn-success" value="Enviar">

        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo_Empleado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sueldo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre_Pila)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido_Paterno)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sueldo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre_Pila)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido_Paterno)
                    </td>
                </tr>
            }
        </table>

    }
</div>

Minimarket_Raphi/Views/Empleado/Index.cshtml
@model IEnumerable<Minimarket_Raphi.Models.Empleado>

@{
    ViewBag.Title = "Administración de Empleado";
}

<div class="jumbotron">
    <h2>Tabla Empleado</h2>
    @Html.ActionLink("NuevoEmpleado", "NuevoEmpleado", "Empleado", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("ActualizarEmpleado", "ActualizarEmpleado", "Empleado", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("EliminarEmpleado", "EliminarEmpleado", "Empleado", null, new { @class = "btn btn-primary btn-lg" })


    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo_Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sueldo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Pila)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido_Paterno)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo_Empleado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sueldo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_Pila)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido_Paterno)
                </td>

            </tr>
        }
    </table>
</div>

Minimarket_Raphi/Views/Empleado/NuevoEmpleado.cshtml
@using Minimarket_Raphi.Models
@using System.Data.Entity.Core.Objects;
@model IEnumerable<Minimarket_Raphi.Models.Empleado>
@{
    ViewBag.Title = "NuevoEmpleado";
}
<div class="jumbotron">
    <h2>Nuevo Empleado</h2>
    @using (Html.BeginForm("NuevoEmpleado", "Empleado", FormMethod.Post))
    {
        <style>
            div {
                margin-bottom: 10px;
            }

            label {
                display: inline-block;
                width: 150px;
                text-align: right;
            }
        </style>

        @Html.Label("Ingrese código:")
        @Html.TextBox("Codigo_Empleado")
        <br>
        @Html.Label("Ingrese Nombre:")
        @Html.TextBox("Nombre_Pila")
        <br>
        @Html.Label("Ingrese Apellido Paterno:")
        @Html.TextBox("Apellido_Paterno")
        <br>
        @Html.Label("Ingrese Apellido Materno:")
        @Html.TextBox("Apellido_Materno")
        <br>
        @Html.Label("Ingrese Sueldo:")
        @Html.TextBox("Sueldo")
        <br>
        @Html.Label("Fecha de Modificación")
        @Html.TextBox("Fecha_Modificacion")
        <br>
        @Html.Label("Acción Ejecutada:")
        @Html.TextBox("Accion_Ejecutada")
        <br>


        <input type="submit" class="btn btn-success" value="Enviar">

    }
</div>